
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: DuVMcrar7AF1024
      MYSQL_DATABASE: exampledb
      MYSQL_USER: hugo
      MYSQL_PASSWORD: 0KWeDPEsyxUYIWYPx
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-local
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: DuVMcrar7AF1024
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - backend
      
volumes:
  mysql-data:

networks:
  backend:
