
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: passRoot123
      MYSQL_DATABASE: exampledb
      MYSQL_USER: hugo
      MYSQL_PASSWORD: passUsr123
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-local
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    volumes:
    - ./pma-config/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    depends_on:
      - mysql
    networks:
      - backend
      
volumes:
  mysql-data:

networks:
  backend:
